CREATE TABLE Users (
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    email VARCHAR (100) NOT NULL PRIMARY KEY,
    user_password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL  DEFAULT CURRENT_TIME
);

ALTER TABLE Users
DROP PRIMARY KEY
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST;
